import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <style jsx>
        {
          `
          .myimg
          {
            border: 4px solid black;
            margin: 20px 0px;
            padding: 2px 2px 0px 2px;
            border-radius:100%
          }
          .heading
          {
            font-size:25px;
            color:red;
            margin-top:20px;
          }
          `
        }
      </style>
        <div className="myimg">
        <Image className={styles.imgcomp} src="/image.png" height={300} width={300} alt="The Coder"></Image>
        </div>
        <div className={styles.center}>
          <h1 className={styles.title}>Curious Blogs</h1>
          <p className={styles.description}>Curious Blogs is just being someone who is curious about a blog.</p>
        </div>
        <h1 className="heading">Latest Blogs</h1>
        <div className={styles.blogs}>
         <div className={styles.blogitem}>
          <h3>Javascript is a popular language?</h3>
          <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. </p>
          <button className={styles.btn}>Read More</button>
          </div>
          <div className={styles.blogitem}>
          <h3>Javascript is a popular language?</h3>
          <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. </p>
          <button className={styles.btn}>Read More</button>
          </div>
          <div className={styles.blogitem}>
          <h3>Javascript is a popular language?</h3>
          <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. </p>
          <button className={styles.btn}>Read More</button>
          </div>
          <div className={styles.blogitem}>
          <h3>Javascript is a popular language?</h3>
          <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. </p>
          <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>
    </>
  );
}
